FROM node:23-alpine
WORKDIR /app


COPY . .

EXPOSE 3000
CMD [ "node","index.js" ]

# docker build -t lab09:api .
# docker run -itd -p 4007:3000 lab09:api
# docker run -itd -p 4008:3000 lab09:api
# son dos intancias ejecutando

